// Languages available for courses, keyed by ISO 639-1 code. Names are
// endonyms so every user can find their own language. Every language here
// has a Wiktionary edition for definitions.
export const courseLanguages = {
  en: 'English',
  es: 'Español',
  de: 'Deutsch',
  fr: 'Français',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  pl: 'Polski',
  uk: 'Українська',
  be: 'Беларуская',
  tr: 'Türkçe',
  nl: 'Nederlands',
  sv: 'Svenska',
  no: 'Norsk',
  da: 'Dansk',
  fi: 'Suomi',
  is: 'Íslenska',
  cs: 'Čeština',
  sk: 'Slovenčina',
  hu: 'Magyar',
  ro: 'Română',
  bg: 'Български',
  sr: 'Српски',
  hr: 'Hrvatski',
  bs: 'Bosanski',
  sl: 'Slovenščina',
  mk: 'Македонски',
  sq: 'Shqip',
  el: 'Ελληνικά',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  ga: 'Gaeilge',
  cy: 'Cymraeg',
  mt: 'Malti',
  eu: 'Euskara',
  ca: 'Català',
  gl: 'Galego',
  af: 'Afrikaans',
  eo: 'Esperanto',
  la: 'Latina',
  ka: 'ქართული',
  hy: 'Հայերեն',
  az: 'Azərbaycanca',
  kk: 'Қазақша',
  ky: 'Кыргызча',
  uz: 'Oʻzbekcha',
  tg: 'Тоҷикӣ',
  fa: 'فارسی',
  ar: 'العربية',
  he: 'עברית',
  ur: 'اردو',
  hi: 'हिन्दी',
  bn: 'বাংলা',
  pa: 'ਪੰਜਾਬੀ',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  ml: 'മലയാളം',
  kn: 'ಕನ್ನಡ',
  mr: 'मराठी',
  si: 'සිංහල',
  ne: 'नेपाली',
  th: 'ไทย',
  lo: 'ລາວ',
  my: 'မြန်မာ',
  km: 'ខ្មែរ',
  vi: 'Tiếng Việt',
  id: 'Bahasa Indonesia',
  ms: 'Bahasa Melayu',
  tl: 'Tagalog',
  ja: '日本語',
  zh: '中文',
  ko: '한국어',
  mn: 'Монгол',
  sw: 'Kiswahili',
  am: 'አማርኛ',
};

/// Native names of the supported UI languages, keyed by code.
export const uiLanguageNames = {
  en: 'English',
  ru: 'Русский',
  es: 'Español',
  de: 'Deutsch',
  fr: 'Français',
  pt: 'Português',
  it: 'Italiano',
  pl: 'Polski',
  tr: 'Türkçe',
  zh: '中文',
  ja: '日本語',
};

export function languageName(code) {
  return courseLanguages[code] || code;
}

/// Compact course label, e.g. "English → Polski".
export function courseLabel(targetLang, nativeLang) {
  return `${languageName(targetLang)} → ${languageName(nativeLang)}`;
}
